[workspace]
resolver = "2"
members = ["ui", "web", "desktop", "mobile", "api", "backend", "shared"]

[workspace.dependencies]
dioxus = { version = "0.6.0" }

ui = { path = "ui" }
api = { path = "api" }
backend = { path = "backend" }
