[workspace]
members = [
    "shared",
    "client",
    "server",
]
resolver = "3"

[workspace.dependencies]
tonic = {version="0.13.1"}
prost = "0.13"
tonic-build = "0.13.1"
tokio-stream = "0.1.11"
tokio = { version = "1.23.1", features = ["rt-multi-thread", "fs"] }
