[package]
name = "ironscribe"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "filetransfer-client"
path = "src/filetransfer-client.rs"

[[bin]]
name = "filetransfer-server"
path = "src/filetransfer-server.rs"

[[bin]]
name = "gpt-client"
path = "src/gpt-client.rs"

[[bin]]
name = "gpt-server"
path = "src/gpt-server.rs"


[dependencies]
tonic = "*"
prost = "0.13"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1", features = ["v4"]}
async-stream = "0.3"
tokio-stream = "0.1"

[build-dependencies]
tonic-build = "*"