[package]
name = "ironscribe"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tonic = { version = "0.10", features = ["transport"] }
prost = "0.12"
axum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
serde_bytes = "0.11.17"

[build-dependencies]
tonic-build = "*"
