[workspace]
resolver = "2"
members = ["ui", "web", "desktop", "mobile", "api", "core"]

[workspace.dependencies]
dioxus = { version = "0.6.0" }

ui = { path = "ui" }
api = { path = "api" }
core = { path = "core" }
