[package]
name = "ironscribe"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "client"

[[bin]]
name = "server"

[dependencies]
tonic = { version = "0.10", features = ["transport"] }
prost = "0.12"

[build-dependencies]
tonic-build = "*"