[workspace]
members = [
    "shared",
    "client",
    "server",
    "protobuf"
]
resolver = "3"

[workspace.dependencies]
tonic = {version="0.13.1", features = ["tls-ring"]}
prost = "0.13"
tonic-build = "0.13.1"
