[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
ironscribe-common = { path = "../ironscribe-common"}
tonic = "*"
prost = "0.13"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }