[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
tokio-stream.workspace = true
shared = { path = "../shared"}
tonic.workspace = true
anyhow.workspace = true
chrono = "0.4.41"
sha2 = "0.10.9"
tracing = "0.1.41"
