[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
shared = { path = "../shared"}
tonic.workspace = true
anyhow = "1.0.98"
uuid = { version = "1", features = ["v4"]}
sha2 = "0.10.9"
