[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
shared = { path = "../shared"}
tonic.workspace = true
anyhow = "1.0.98"
chrono = "0.4.41"
sha2 = "0.10.9"
