[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic.workspace = true
prost.workspace = true
sha2 = "0.10.9"
anyhow.workspace = true
adler32 = "1.2.0"

[build-dependencies]
tonic-build.workspace = true
