[package]
name = "serverbin"
version = "0.1.0"
edition = "2021"

[dependencies]
ui = { workspace = true }
tokio = { workspace = true }
dioxus = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
axum = { workspace = true }
